# Generated by Django 2.2.5 on 2019-11-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email_adress', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Visior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email_adress', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField(default=0)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField()),
            ],
        ),
    ]
