# Generated by Django 2.2.5 on 2019-11-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visior',
            new_name='Visitor',
        ),
    ]
