# Generated by Django 2.2.5 on 2019-11-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_visitor_host_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='host_name',
            new_name='host',
        ),
    ]
