# Generated by Django 2.2.5 on 2019-11-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_auto_20191121_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
