# Generated by Django 2.2.5 on 2019-11-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_auto_20191121_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
