# Generated by Django 2.2.5 on 2019-11-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_auto_20191121_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='email_adress',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='email_adress',
            new_name='email_address',
        ),
        migrations.AddField(
            model_name='host',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
